name: DistanceOptimization
author: Vovari2
version: '1.0'
main: me.vovari2.distanceoptimization.DistanceOptimization
api-version: '1.21'

commands:
  distanceoptimization:
    aliases: ["do"]

permissions:
  distance_optimization.*:
    description: "Permission to perform all actions of the DistanceOptimization plugin, except \"distance_optimization.protect\""
    default: false

  distance_optimization.help:
    description: "Permission to use the help command (/do help)"
    default: false
    children:
      distance_optimization.commands: true
  distance_optimization.reload:
    description: "Permission to use the reload command (/do reload)"
    default: false
    children:
      distance_optimization.commands: true
